apiVersion: v1
kind: PersistentVolume
metadata:
  name: webblast-dbs
spec:
  storageClassName: ""
  capacity:
    storage: 100G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: test-cluster-camacho-pd
    fsType: ext4
